[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
smartcontractkit-chainlink-evm = "0.3.2"
forge-std = "1.11.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
